apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    name: my-app-label
spec:
  containers:
    - name: simple-webapp
      image: nginx
      ports:
        - containerPort: 8080
  serviceAccount: my-sa