apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    name: my-app-label
spec:
  containers:
    - name: simple-webapp
      image: nginx
      ports:
        - containerPort: 8080
# Method 1 - env
      envFrom:
      - secretRef:
          name: app-secret
# method 2 - single env
      env:
        - name: DB_Password
          valueFrom:
            secretRefKey:
              name: app-secret
              key: DB_Password
# method 3 - volume
# ls /opt/app-secret-volumes
      volumes:
        - name: app-secret-volume
          secret:
            secretName: app-secret